#!/bin/bash

NORMAL=$(tput sgr0)
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)

while read line
do
    if [[ $line =~ ^WARNING ]]; then
        echo -e "$YELLOW$line$NORMAL"
    elif [[ $line =~ ^ERROR ]]; then
        echo -e "$RED$line$NORMAL"
    elif [[ $line =~ ^Number\ of\  ]]; then
        echo -e "$GREEN$line$NORMAL"
    elif [ ! -z $ALLMESSAGES ]; then
        echo "$line"
    fi
done
